// Curated IDX ticker list — top liquid names + frequent right-issue issuers.
// Used for fast prefix-match suggestions; Yahoo Finance fills the long tail.
export const IDX_TICKERS: ReadonlyArray<readonly [string, string]> = [
  // Banks
  ['BBCA', 'Bank Central Asia Tbk'],
  ['BBRI', 'Bank Rakyat Indonesia (Persero) Tbk'],
  ['BMRI', 'Bank Mandiri (Persero) Tbk'],
  ['BBNI', 'Bank Negara Indonesia (Persero) Tbk'],
  ['BRIS', 'Bank Syariah Indonesia Tbk'],
  ['BBTN', 'Bank Tabungan Negara (Persero) Tbk'],
  ['BBKP', 'Bank KB Bukopin Tbk'],
  ['BNGA', 'Bank CIMB Niaga Tbk'],
  ['BNII', 'Bank Maybank Indonesia Tbk'],
  ['BJBR', 'Bank Pembangunan Daerah Jawa Barat & Banten Tbk'],
  ['BJTM', 'Bank Pembangunan Daerah Jawa Timur Tbk'],
  ['BNLI', 'Bank Permata Tbk'],
  ['MEGA', 'Bank Mega Tbk'],
  ['NISP', 'Bank OCBC NISP Tbk'],
  ['PNBN', 'Bank Pan Indonesia Tbk'],
  ['ARTO', 'Bank Jago Tbk'],
  ['AGRO', 'Bank Raya Indonesia Tbk'],
  ['BANK', 'Bank Aladin Syariah Tbk'],
  ['AMAR', 'Bank Amar Indonesia Tbk'],
  ['BABP', 'Bank MNC Internasional Tbk'],
  // Telco
  ['TLKM', 'Telkom Indonesia (Persero) Tbk'],
  ['EXCL', 'XL Axiata Tbk'],
  ['ISAT', 'Indosat Tbk'],
  ['FREN', 'Smartfren Telecom Tbk'],
  ['TOWR', 'Sarana Menara Nusantara Tbk'],
  ['TBIG', 'Tower Bersama Infrastructure Tbk'],
  ['MTEL', 'Dayamitra Telekomunikasi Tbk'],
  // Consumer
  ['UNVR', 'Unilever Indonesia Tbk'],
  ['ICBP', 'Indofood CBP Sukses Makmur Tbk'],
  ['INDF', 'Indofood Sukses Makmur Tbk'],
  ['MYOR', 'Mayora Indah Tbk'],
  ['GGRM', 'Gudang Garam Tbk'],
  ['HMSP', 'HM Sampoerna Tbk'],
  ['KLBF', 'Kalbe Farma Tbk'],
  ['SIDO', 'Industri Jamu dan Farmasi Sido Muncul Tbk'],
  ['KAEF', 'Kimia Farma Tbk'],
  ['INAF', 'Indofarma Tbk'],
  ['CPIN', 'Charoen Pokphand Indonesia Tbk'],
  ['JPFA', 'Japfa Comfeed Indonesia Tbk'],
  // Automotive / Industrials
  ['ASII', 'Astra International Tbk'],
  ['AUTO', 'Astra Otoparts Tbk'],
  ['GJTL', 'Gajah Tunggal Tbk'],
  ['IMAS', 'Indomobil Sukses Internasional Tbk'],
  // Property / Construction
  ['BSDE', 'Bumi Serpong Damai Tbk'],
  ['CTRA', 'Ciputra Development Tbk'],
  ['PWON', 'Pakuwon Jati Tbk'],
  ['SMRA', 'Summarecon Agung Tbk'],
  ['LPKR', 'Lippo Karawaci Tbk'],
  ['ASRI', 'Alam Sutera Realty Tbk'],
  ['WIKA', 'Wijaya Karya (Persero) Tbk'],
  ['WSKT', 'Waskita Karya (Persero) Tbk'],
  ['PTPP', 'PP (Persero) Tbk'],
  ['ADHI', 'Adhi Karya (Persero) Tbk'],
  ['WTON', 'Wijaya Karya Beton Tbk'],
  ['JSMR', 'Jasa Marga (Persero) Tbk'],
  // Energy / Mining
  ['ADRO', 'Adaro Energy Indonesia Tbk'],
  ['PTBA', 'Bukit Asam Tbk'],
  ['ITMG', 'Indo Tambangraya Megah Tbk'],
  ['HRUM', 'Harum Energy Tbk'],
  ['INDY', 'Indika Energy Tbk'],
  ['BUMI', 'Bumi Resources Tbk'],
  ['MEDC', 'Medco Energi Internasional Tbk'],
  ['ENRG', 'Energi Mega Persada Tbk'],
  ['ANTM', 'Aneka Tambang Tbk'],
  ['INCO', 'Vale Indonesia Tbk'],
  ['TINS', 'Timah Tbk'],
  ['MDKA', 'Merdeka Copper Gold Tbk'],
  ['MBMA', 'Merdeka Battery Materials Tbk'],
  ['NCKL', 'Trimegah Bangun Persada Tbk'],
  ['BRMS', 'Bumi Resources Minerals Tbk'],
  ['AMMN', 'Amman Mineral Internasional Tbk'],
  ['PGAS', 'Perusahaan Gas Negara Tbk'],
  ['ELSA', 'Elnusa Tbk'],
  // Plantation
  ['AALI', 'Astra Agro Lestari Tbk'],
  ['LSIP', 'PP London Sumatra Indonesia Tbk'],
  ['SIMP', 'Salim Ivomas Pratama Tbk'],
  ['SGRO', 'Sampoerna Agro Tbk'],
  ['DSNG', 'Dharma Satya Nusantara Tbk'],
  // Cement
  ['SMGR', 'Semen Indonesia (Persero) Tbk'],
  ['INTP', 'Indocement Tunggal Prakarsa Tbk'],
  ['SMBR', 'Semen Baturaja (Persero) Tbk'],
  // Retail / Tech
  ['ACES', 'Aspirasi Hidup Indonesia Tbk'],
  ['ERAA', 'Erajaya Swasembada Tbk'],
  ['MAPI', 'Mitra Adiperkasa Tbk'],
  ['MAPA', 'Map Aktif Adiperkasa Tbk'],
  ['LPPF', 'Matahari Department Store Tbk'],
  ['AMRT', 'Sumber Alfaria Trijaya Tbk'],
  ['MIDI', 'Midi Utama Indonesia Tbk'],
  ['GOTO', 'GoTo Gojek Tokopedia Tbk'],
  ['BUKA', 'Bukalapak.com Tbk'],
  ['EMTK', 'Elang Mahkota Teknologi Tbk'],
  ['SCMA', 'Surya Citra Media Tbk'],
  ['MNCN', 'Media Nusantara Citra Tbk'],
  // Conglomerates / Investment
  ['BRPT', 'Barito Pacific Tbk'],
  ['BREN', 'Barito Renewables Energy Tbk'],
  ['TPIA', 'Chandra Asri Pacific Tbk'],
  ['SRTG', 'Saratoga Investama Sedaya Tbk'],
  ['DSSA', 'Dian Swastatika Sentosa Tbk'],
  ['UNTR', 'United Tractors Tbk'],
  ['INKP', 'Indah Kiat Pulp & Paper Tbk'],
  ['TKIM', 'Pabrik Kertas Tjiwi Kimia Tbk'],
  // Transport / Logistics / Airline
  ['GIAA', 'Garuda Indonesia (Persero) Tbk'],
  ['CMNP', 'Citra Marga Nusaphala Persada Tbk'],
  ['BIRD', 'Blue Bird Tbk'],
  // Healthcare / Hospitals
  ['MIKA', 'Mitra Keluarga Karyasehat Tbk'],
  ['HEAL', 'Medikaloka Hermina Tbk'],
  ['SILO', 'Siloam International Hospitals Tbk'],
  // Misc liquid
  ['BFIN', 'BFI Finance Indonesia Tbk'],
  ['CASA', 'Capital Financial Indonesia Tbk'],
] as const;